# Generated by Django 5.0 on 2025-05-17 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_profile_lan_profile_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lan',
            new_name='lat',
        ),
    ]
