# Generated by Django 5.0 on 2025-06-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_chatimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
